[pytest]
filterwarnings =
    ignore:pkg_resources is deprecated as an API:DeprecationWarning:face_recognition_models
    ignore:Deprecated call to `pkg_resources\.declare_namespace\('google'\)`:DeprecationWarning:pkg_resources
    ignore:Deprecated call to `pkg_resources\.declare_namespace\('sphinxcontrib'\)`:DeprecationWarning:pkg_resources
    ignore:Deprecated call to `pkg_resources\.declare_namespace\('zope'\)`:DeprecationWarning:pkg_resources
