"""add_id_card_tables

Revision ID: 327c3c6d717a
Revises: d4fdb664ff01
Create Date: 2026-05-03 17:45:40.207442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '327c3c6d717a'
down_revision = 'd4fdb664ff01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('id_card_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('logo_path', sa.String(length=255), nullable=True),
    sa.Column('principal_name', sa.String(length=100), nullable=True),
    sa.Column('principal_title', sa.String(length=100), nullable=True),
    sa.Column('principal_signature_path', sa.String(length=255), nullable=True),
    sa.Column('college_phone', sa.String(length=30), nullable=True),
    sa.Column('college_website', sa.String(length=200), nullable=True),
    sa.Column('card_color', sa.String(length=20), nullable=True),
    sa.Column('accent_color', sa.String(length=20), nullable=True),
    sa.Column('valid_years', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_id_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('photo_path', sa.String(length=255), nullable=True),
    sa.Column('card_number', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected'), nullable=False),
    sa.Column('rejection_note', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_number'),
    sa.UniqueConstraint('student_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_id_cards')
    op.drop_table('id_card_templates')
    # ### end Alembic commands ###
