"""add last_arrival_date to student_locations

Revision ID: 5e89f810c444
Revises: 903ee74ec8ac
Create Date: 2026-05-03 12:40:09.700868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e89f810c444'
down_revision = '903ee74ec8ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_arrival_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_locations', schema=None) as batch_op:
        batch_op.drop_column('last_arrival_date')

    # ### end Alembic commands ###
