"""add college_settings table

Revision ID: 903ee74ec8ac
Revises: a49a0ae26c47
Create Date: 2026-05-03 08:03:13.075456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '903ee74ec8ac'
down_revision = 'a49a0ae26c47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('college_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('college_name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('college_settings')
    # ### end Alembic commands ###
