"""add parent tables

Revision ID: efcdcebbde86
Revises: 
Create Date: 2026-05-03 07:33:20.917845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efcdcebbde86'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parent_students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('relationship', sa.Enum('father', 'mother', 'guardian', 'other'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_id', 'student_id', name='uq_parent_student')
    )
    op.create_table('teacher_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('on_campus', 'in_class', 'unavailable', 'off_campus'), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_id')
    )
    op.create_table('class_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('alert_date', sa.Date(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('recipient_count', sa.Integer(), nullable=True),
    sa.Column('triggered_by', sa.Enum('auto', 'manual'), nullable=True),
    sa.ForeignKeyConstraint(['slot_id'], ['timetable_slots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slot_id', 'alert_date', name='uq_alert_per_day')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('class_alerts')
    op.drop_table('teacher_statuses')
    op.drop_table('parent_students')
    # ### end Alembic commands ###
